FROM php

# install gd mcrypt extensions
RUN apt-get update && apt-get install -y \
	apt-utils \
	libmcrypt-dev \
	libfreetype6-dev \
	libpng-dev \
	libjpeg-dev \
	libxslt-dev \
	libxml2-dev \
	&& docker-php-ext-install -j$(nproc) mcrypt \
        && docker-php-ext-configure gd --with-png-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
        && docker-php-ext-install -j$(nproc) gd

# install sockets bcmath soap
RUN docker-php-ext-install sockets \
	&& docker-php-ext-install soap \
	&& docker-php-ext-install bcmath

# install ssh2
ENV SSH2_VERSION 0.13
RUN apt-get install -y libssh2-1-dev \
	&& curl -L -o /tmp/ssh2.tgz http://pecl.php.net/get/ssh2-0.13.tgz \
	&& tar zxf /tmp/ssh2.tgz \
	&& rm -r /tmp/ssh2.tgz \
	&& mkdir -p /usr/src/php/ext \
	&& mv ssh2-$SSH2_VERSION /usr/src/php/ext/ssh2 \
	&& docker-php-ext-install ssh2 \
	&& rm -rf /usr/src/php

# install mysql mysqli extensions
RUN docker-php-ext-install mysql \
	&& docker-php-ext-install pdo_mysql \
	&& docker-php-ext-install mysqli

# replace the php.ini from the host
COPY ./php/conf/php.ini /usr/local/etc/php/php.ini 

# install redis extensions
ENV PHPREDIS_VERSION 3.1.3
RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mkdir -p /usr/src/php/ext \
    && mv phpredis-$PHPREDIS_VERSION /usr/src/php/ext/redis \
    && docker-php-ext-install redis \
    && rm -rf /usr/src/php

# install memcached extensions
ENV PHPMEMCACHED_VERSION 2.2.0
RUN apt-get install -y libmemcached-dev \
	libevent-dev \
	&& curl -L -o /tmp/memcached.tgz http://pecl.php.net/get/memcached-$PHPMEMCACHED_VERSION.tgz \
	&& tar zxf /tmp/memcached.tgz \
	&& rm -r /tmp/memcached.tgz \
	&& mkdir -p /usr/src/php/ext \
	&& mv memcached-$PHPMEMCACHED_VERSION /usr/src/php/ext/memcached \
	&& docker-php-ext-install memcached \
	&& rm -rf /usr/src/php

# install memcache extensions
ENV PHPMEMCACHE_VERSION 2.2.7
RUN curl -L -o /tmp/memcache.tgz http://pecl.php.net/get/memcache-$PHPMEMCACHE_VERSION.tgz \
        && tar zxf /tmp/memcache.tgz \
        && rm -r /tmp/memcache.tgz \
        && mkdir -p /usr/src/php/ext \
        && mv memcache-$PHPMEMCACHE_VERSION /usr/src/php/ext/memcache \
        && docker-php-ext-install memcache \
        && rm -rf /usr/src/php
